server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: intanciasmulti
          uri: https://github.com/AngelKN/Proyecto
          search-paths: ServicioConfigData
  aplication:
    name: ServicioConfig